[package]
name = "orderbook"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.5"
num_cpus = "1.17.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1.4.0", features = ["rt", "rt-multi-thread", "macros"] }
